# Numpy

### Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built.  


## NpArrays
```NumPy.array( object , dtype=None ,order=None,ndmin=0)```

In [1]:
import numpy as np
a = np.array([1,2,3], dtype = float, order = 'c')
#Order can be C (row), F (column), A (major)
print(a)

[1. 2. 3.]


In [2]:
c = np.array([4,5,6])
print(c, "\n") 
d = np.array([[4,5,7],[1,2,3]])
print(d)

[4 5 6] 

[[4 5 7]
 [1 2 3]]


In [3]:
#Range Array
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


### Dimension and Shape And Type And Size

#### Tells the dimension of the object (1d, 2d or 3d) 
```
    object.shape
```
-----------
#### Tells the Shape i.e the rows and columns 

```
    object.ndim
```
--------------------
#### Tells the type of the datatype such as int32 int8

```
    object.dtype
```
--------------------------
#### Tells the size of the object that is int[n]/8 soo int32 => 4
```
    object.itemsize
```

In [4]:
#Shape
print(c.shape)
print(d.shape)

#Dimensions
print(c.ndim)
print(d.ndim)

#Type and Size
print(d.dtype)
print(d.itemsize)

(3,)
(2, 3)
1
2
int32
4


## Accessing/Changing specific elements, rows and columns

#### To get the specific Element of the list 
NOTE: Starts from the 0th Index not the 1st Index

```
    object[row_value, column_value]
```
-----------
#### To get the specifc row

```
    object[row_no, :]
```
-----------
#### To get the entire column

```
    object[:, column_no]
```
-----------
#### Replace an element in the array

```
    object[row_value, column_value] = new number
```

In [5]:
f = np.array([[1,2,3,4,6,7,8], [10,11,12,13,14,15,16]], dtype = 'int64')
print(f)

[[ 1  2  3  4  6  7  8]
 [10 11 12 13 14 15 16]]


In [6]:
#Specific element
f[1,-1] 

16

In [7]:
#Specifc row
f[1, :]

array([10, 11, 12, 13, 14, 15, 16], dtype=int64)

In [8]:
#Specifc Column
f[:, 5]

array([ 7, 15], dtype=int64)

In [9]:
#Replace element
f[1,-1] = 20
print(f)

[[ 1  2  3  4  6  7  8]
 [10 11 12 13 14 15 20]]


## Different types of Arrays

In [10]:
#Zeros Matrix
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
#Ones Matrix
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
#Any number
a = np.full((2,2), 99)
print(a)

[[99 99]
 [99 99]]


In [13]:
#Identity Matrix
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
#Random number matrix between 0 and 1
a = np.random.rand(2,2)
print(a)

[[0.21338515 0.04859005]
 [0.08105752 0.3401881 ]]


In [15]:
#Random number matrix any number
a = np.random.randint(-4,5, size = (4,5))
print(a)

[[-3  1  4  4  3]
 [ 2 -2  2  3 -3]
 [-3  1  3  3  2]
 [-1 -3 -3 -4  1]]


In [16]:
#Repeat an Array
a = np.array([[2,3]])
r1 = np.repeat(a, 2, axis = 0)
print(r1)

[[2 3]
 [2 3]]


In [17]:
#TASK
#Create an array of 5 rows and columns with 1 row and column surrounding zeroes and the middle element be 9
a = np.ones((5,5), dtype = 'int32')
b = np.zeros((3,3), dtype = 'int32')
b[1,1] = 9
a[1:4,1:4] = b

print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [18]:
#Copying Arrays
a = np.array([1,2,3])
b = a 
print('B output', b)
print('A output', a)

b[0] = 100

print('B output', b)
print('A output', a)


B output [1 2 3]
A output [1 2 3]
B output [100   2   3]
A output [100   2   3]


In [19]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print('A: ', a)
print('B: ', b)

A:  [1 2 3]
B:  [100   2   3]


## Maths

In [20]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [21]:
a + 2

array([3, 4, 5, 6])

In [22]:
a - 2

array([-1,  0,  1,  2])

In [23]:
a * 2

array([2, 4, 6, 8])

In [24]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [25]:
b = np.array([4,5,6,5])
b+a

array([5, 7, 9, 9])

## Linear Algebra

In [26]:
# Matrix Multiplication
a = np.ones((2,2))
b = np.full((2,3), 2)

result = np.matmul(a,b)
print(result)


[[4. 4. 4.]
 [4. 4. 4.]]


In [27]:
# Find the determinant
a = np.identity(3)
np.linalg.det(a)

1.0

In [28]:
# Find the inverse
a = np.random.randint(1,5, size = (2,2), dtype = 'int32')
print(a)
np.linalg.inv(a)

[[3 4]
 [2 3]]


array([[ 3., -4.],
       [-2.,  3.]])

## Stats



In [29]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
#Basic Stats
print(np.min(a))
print(np.max(a))
print(np.sum(a))
print(np.sum(a))
print(np.median(a))

1
8
36
36
4.5


In [31]:
#Sorting
a = np.random.randint(1,10, size=(2,5))
print(a)
sort = np.sort(a)
print(sort)

[[9 7 1 4 4]
 [8 3 2 8 8]]
[[1 4 4 7 9]
 [2 3 8 8 8]]


In [32]:
#Unique Element
np.unique(a)

array([1, 2, 3, 4, 7, 8, 9])

## Reshaping 

In [33]:
#Reshaping the array
before = np.array([[1,2,3,4], [4,5,6,7]])
print(before)
after = np.reshape(before, (4,2))
print(after)

[[1 2 3 4]
 [4 5 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [34]:
#Vertical Stacks
v1 = np.ones((2,4))
v2 = np.zeros((2,4))
np.vstack((v1,v2))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
#Horizontal Stack
h1 = np.ones((1,4))
h2 = np.zeros((1,4))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0., 0., 0.]])